name = "interactive-randombox"
# Cloudflare Pages - Next.js Static Export
pages_build_output_dir = "./out"
compatibility_date = "2024-09-13"
compatibility_flags = ["nodejs_compat"]

# 환경변수는 Cloudflare 대시보드에서 설정
# 또는 wrangler pages secret put 명령어 사용