name = "interactive-randombox"
# Framework preset: Next.js, Build command: npx @cloudflare/next-on-pages@1
pages_build_output_dir = ".vercel/output/static"

# 환경변수는 Cloudflare 대시보드에서 설정
# 또는 wrangler pages secret put 명령어 사용
